spring:
  application:
    name: finance
  datasource:
    hikari:
      maximum-pool-size: 10 # ?????
      minimum-idle: 2 # ??????
      idle-timeout: 30000 # ??????????
      connection-timeout: 20000 # ??????????
      max-lifetime: 1800000 # ????????
    url: jdbc:postgresql://192.168.14.2:5432/finance-sec?currentSchema=public&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: system
    password: Seer@bigdata
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      # 地址
      host: 192.168.14.2
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 1
      # 密码
      password: ''
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms